title: Blog || Ishan Lakhwani
description: "My personal blog"
author:
  name: "Ishan Lakhwani"
  email: "ishan.lakhwani@gmail.com"
  url: "https://bluntbrain.github.io/blog/"

baseurl: /

source: .
destination: ./_site
permalink: /:title
paginate: 3
paginate_path: /page/:num/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

future: true
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
owner : "bluntbrain"
year : "2021"
